"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-15 18:19:44.377943
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('account_type', sa.String(length=16), nullable=False),
    sa.Column('whitelabel_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('account_type_explicitly_set', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('monthly_fee_cents', sa.Integer(), nullable=False),
    sa.Column('base_payments_included', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('max_stores', sa.Integer(), nullable=True),
    sa.Column('max_keys_per_account', sa.Integer(), nullable=False),
    sa.Column('max_webhooks_per_account', sa.Integer(), nullable=False),
    sa.Column('csv_export_enabled', sa.Boolean(), nullable=False),
    sa.Column('priority_support', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('can_manage_stores', sa.Boolean(), nullable=False),
    sa.Column('key_prefix', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_account_id'), ['account_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_account_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)

    op.create_table('plan_ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('amount_cents_delta', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_payments_count', sa.Integer(), nullable=False),
    sa.Column('total_volume_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_plan_ledger_account_period', ['account_id', 'period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_ledger_entries_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_ledger_entries_period_month'), ['period_month'], unique=False)

    op.create_table('plan_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_subscriptions_account_id'), ['account_id'], unique=False)

    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('created_via', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('owner_name', sa.String(length=120), nullable=True),
    sa.Column('owner_phone', sa.String(length=40), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=15), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('redirect_success_url', sa.Text(), nullable=True),
    sa.Column('redirect_failure_url', sa.Text(), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('brand_color', sa.String(length=16), nullable=True),
    sa.Column('logo_image_url', sa.Text(), nullable=True),
    sa.Column('whitelabel_css', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_id', name='uq_store_account_external')
    )
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stores_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stores_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_stores_status'), ['status'], unique=False)

    op.create_table('webhook_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('secret_key', sa.String(length=128), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_endpoints_account_id'), ['account_id'], unique=False)

    op.create_table('payment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=24), nullable=False),
    sa.Column('raw_link', sa.Text(), nullable=False),
    sa.Column('merchant_account_id', sa.String(length=120), nullable=False),
    sa.Column('merchant_name', sa.String(length=120), nullable=True),
    sa.Column('payway_client_id', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('verification', sa.String(length=16), nullable=False),
    sa.Column('is_sandbox', sa.Boolean(), nullable=False),
    sa.Column('min_amount_cents', sa.Integer(), nullable=False),
    sa.Column('max_amount_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_links_store_id'), ['store_id'], unique=True)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('payment_link_id', sa.Integer(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('qr_string', sa.Text(), nullable=False),
    sa.Column('qr_md5', sa.String(length=32), nullable=True),
    sa.Column('bill_number', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bakong_ref', sa.String(length=255), nullable=True),
    sa.Column('gateway_status_raw', sa.JSON(), nullable=True),
    sa.Column('attempt_history', sa.JSON(), nullable=True),
    sa.Column('reissued_from_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_link_id'], ['payment_links.id'], ),
    sa.ForeignKeyConstraint(['reissued_from_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'idempotency_key', name='uq_store_idem')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_payment_link_id'), ['payment_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_qr_md5'), ['qr_md5'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_reissued_from_id'), ['reissued_from_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_store_id'), ['store_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_store_id'), ['store_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_type'), ['type'], unique=False)

    op.create_table('plan_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('period_month', sa.String(length=7), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('base_fee_cents', sa.Integer(), nullable=False),
    sa.Column('usage_payments_count', sa.Integer(), nullable=False),
    sa.Column('overage_payments_count', sa.Integer(), nullable=False),
    sa.Column('overage_fee_cents', sa.Integer(), nullable=False),
    sa.Column('total_due_cents', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chmabapay_payment_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['chmabapay_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['plan_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan_invoices', schema=None) as batch_op:
        batch_op.create_index('ix_plan_invoices_period_month', ['period_month'], unique=False)

    op.create_table('event_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_response_status', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['webhook_endpoints.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'endpoint_id', name='uq_event_endpoint')
    )
    with op.batch_alter_table('event_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_deliveries_endpoint_id'), ['endpoint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_deliveries_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_deliveries_event_id'))
        batch_op.drop_index(batch_op.f('ix_event_deliveries_endpoint_id'))

    op.drop_table('event_deliveries')
    with op.batch_alter_table('plan_invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_invoices_period_month')

    op.drop_table('plan_invoices')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_type'))
        batch_op.drop_index(batch_op.f('ix_events_store_id'))
        batch_op.drop_index(batch_op.f('ix_events_account_id'))

    op.drop_table('events')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_store_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_reissued_from_id'))
        batch_op.drop_index(batch_op.f('ix_payments_reference_id'))
        batch_op.drop_index(batch_op.f('ix_payments_qr_md5'))
        batch_op.drop_index(batch_op.f('ix_payments_public_id'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_link_id'))

    op.drop_table('payments')
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_links_store_id'))

    op.drop_table('payment_links')
    with op.batch_alter_table('webhook_endpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_endpoints_account_id'))

    op.drop_table('webhook_endpoints')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stores_status'))
        batch_op.drop_index(batch_op.f('ix_stores_public_id'))
        batch_op.drop_index(batch_op.f('ix_stores_external_id'))
        batch_op.drop_index(batch_op.f('ix_stores_account_id'))

    op.drop_table('stores')
    with op.batch_alter_table('plan_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_subscriptions_account_id'))

    op.drop_table('plan_subscriptions')
    with op.batch_alter_table('plan_ledger_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_ledger_entries_period_month'))
        batch_op.drop_index(batch_op.f('ix_plan_ledger_entries_account_id'))
        batch_op.drop_index('ix_plan_ledger_account_period')

    op.drop_table('plan_ledger_entries')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_account_id'))

    op.drop_table('api_keys')
    op.drop_table('plans')
    op.drop_table('accounts')
    # ### end Alembic commands ###
